### PR TITLE
Wiki command overhaul

### PR DESCRIPTION
**Pull request by RubenJ01**
Small chance that now instead of sending a link, it will put the brief page description into an embed and post that, along with the link, image and current time.

### CODE REVIEW

**Review by zedchance — CHANGES_REQUESTED** [review]
I like it so far! It looks very nice (I especially like the response on `!b wiki`).

I noticed this:
Screen Shot 2020-03-12 at 6 46 22 PM

It has a hard time when you don't search by the entire name. Maybe when it can't find a result you could fall back on how it previously behaved?

**Comment by RubenJ01** [comment]
> I like it so far! It looks very nice (I especially like the response on `!b wiki`).
> 
> I noticed this:
> Screen Shot 2020-03-12 at 6 46 22 PM
> 
> It has a hard time when you don't search by the entire name. Maybe when it can't find a result you could fall back on how it previously behaved?

Should be fixed with this commit.

**Review by zedchance — CHANGES_REQUESTED** [review]
Everything looks good except the command is now missing the url to the wiki page!

**Comment by RubenJ01** [comment]
You can click on the title of the embed, or is it missing somewhere else?

**Comment by zedchance** [comment]
Screen Shot 2020-03-12 at 7 30 45 PM

It didn't make it over when you added the try catches

**Comment by RubenJ01** [comment]
> Everything looks good except the command is now missing the url to the wiki page!

Fixed in e09cc1d

**Pull request merged**
